name: appchat
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.1
  grpc: ^2.2.0
  oauth2: ^1.6.1
  url_launcher: ^5.4.11
  uni_links: ^0.4.0
  intl: ^0.16.1
  audiofileplayer: ^1.3.1
  mic_stream: ^0.2.1
  login_screen: ^0.6.0

  cupertino_icons: ^0.1.3

flutter:
  uses-material-design: true

  assets:
    - images/background.png
    - images/logo.png
    - images/logo1.png
    - images/logo_chat.png
    - assets/key.json
