name: appchat
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^1.0.1
  grpc: ^2.2.0
  intl: ^0.16.1
  audiofileplayer: ^1.3.1
  login_screen: ^0.6.0
  shared_preferences: ^0.5.8
  cupertino_icons: ^0.1.3
  speech_to_text: ^2.3.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/background.png
    - assets/images/logo.png
    - assets/images/logo1.png
    - assets/images/logo_chat.png
    - assets/key.json
